work_dir: /home/hinard/MBAimCLR/data/gty/AAAI_github/ntu120_cv/mbaimclr_joint/pretext/xset

#weights: /home/hinard/MBAimCLR/data/gty/AAAI_github/ntu120_cv/mbaimclr_joint/pretext/xset/epoch15_model.pt
resume: False

# feeder
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
  data_path: /home/hinard/MBAimCLR/data/gty/action_dataset/ntu120_frame50/xset/train_position.npy
  label_path: /home/hinard/MBAimCLR/data/gty/action_dataset/ntu120_frame50/xset/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# model
model: net.mbaimclr.MBAimCLR
model_args:
  base_encoder: net.DSTformer.DSTformer
  pretrain: True
  dim_feat: 512
  queue_size: 32768
  momentum: 0.999
  Temperature: 0.07
  in_channels: 3
  out_channels: 128
  num_class: 120
  dim_rep: 512
  depth: 4
  num_heads: 8
  mlp_ratio: 2
  num_joints: 25
  clip_len: 50
  dropout_ratio: 0.5
  hidden_dim: 2048


# optim
nesterov: False
weight_decay: 0.01
base_lr: 0.0001
optimizer: SGD
step: [250]

# training
device: [2]
batch_size: 8
test_batch_size: 8
num_epoch: 150
start_epoch: 0
stream: 'joint'

# nearest neighbor mining
topk: 1
mining_epoch: 1000

# log
save_interval: 5
eval_interval: -1
