work_dir: /home/hinard/MBAimCLR/data/gty/AAAI_github/ntu60_cv/mbaimclr_joint/pretext

weights: /home/hinard/MBAimCLR/data/gty/AAAI_github/ntu60_cv/mbaimclr_joint/pretext/epoch1_model.pttest
resume: False

# feeder
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
  data_path: /home/hinard/MBAimCLR/data/gty/action_dataset/ntu60_frame50/xsub/train_position.npy
  label_path: /home/hinard/MBAimCLR/data/gty/action_dataset/ntu60_frame50/xsub/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# model
model: net.mbaimclr.MBAimCLR
model_args:
  base_encoder: net.DSTformer.DSTformer
  pretrain: True
  feature_dim: 128
  queue_size: 32768
  momentum: 0.999
  Temperature: 0.07
  mlp: True
  in_channels: 3
  out_channels: 128
  hidden_dim: 256
  num_class: -1 #for the pretrain
  dropout: 0.5
  depth: 5
  num_heads: 8
  mlp_ratio: 2
  num_joints: 25
  clip_len: 50


# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
step: [250]

# training
device: [2]
batch_size: 32
test_batch_size: 128
num_epoch: 300
start_epoch: 0
stream: 'joint'

# nearest neighbor mining
topk: 1
mining_epoch: 150

# log
save_interval: 5
eval_interval: -1
