work_dir: /home/hinard/MBAimCLR/data/gty/AAAI_github/ntu60_cv/transclr_joint/pretext/

weights: /home/hinard/MBAimCLR/data/gty/AAAI_github/ntu60_cv/transclr_joint/pretext/epoch300_model.pt
resume: True

# feeder
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
  data_path: /home/hinard/MBAimCLR/data/gty/action_dataset/ntu60_frame50/xsub/train_position.npy
  label_path: /home/hinard/MBAimCLR/data/gty/action_dataset/ntu60_frame50/xsub/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# model
model: net.transclr.TransCLR
model_args:
  base_encoder: net.transformer.Transformer
  pretrain: True
  dim_feat: 256
  queue_size: 32768
  momentum: 0.999
  Temperature: 0.07
  in_channels: 3
  out_channels: 128
  num_class: 60
  depth: 4
  num_heads: 8
  mlp_ratio: 4
  num_joints: 25
  clip_len: 50


# optim
nesterov: False
weight_decay: 0.05
base_lr: 0.001
optimizer: SGD
step: [250]

# training
device: [2]
batch_size: 32
test_batch_size: 32
num_epoch: 500
start_epoch: 300
stream: 'joint'

# nearest neighbor mining
topk: 1
mining_epoch: 1000

# log
save_interval: 5
eval_interval: -1
