work_dir: /home/hinard/MBAimCLR/data/gty/AAAI_github/ntu120_cv/mbaimclr_joint/linear_eval/xsub

# weights: /data/gty/released_model/ntu60_xsub_joint.pt
weights: /home/hinard/MBAimCLR/data/gty/AAAI_github/ntu120_cv/mbaimclr_joint/pretext/xsub/epoch15_model.pt
ignore_weights: [encoder_q.head, encoder_k, queue]
resume: True

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /home/hinard/MBAimCLR/data/gty/action_dataset/ntu120_frame50/xsub/train_position.npy
  label_path: /home/hinard/MBAimCLR/data/gty/action_dataset/ntu120_frame50/xsub/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /home/hinard/MBAimCLR/data/gty/action_dataset/ntu120_frame50/xsub/val_position.npy
  label_path: /home/hinard/MBAimCLR/data/gty/action_dataset/ntu120_frame50/xsub/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.mbaimclr.MBAimCLR
model_args:
  base_encoder: net.DSTformer.DSTformer
  pretrain: False
  dim_feat: 512
  queue_size: 32768
  momentum: 0.999
  Temperature: 0.07
  in_channels: 3
  out_channels: 128
  num_class: 120
  dim_rep: 512
  depth: 4
  num_heads: 8
  mlp_ratio: 2
  num_joints: 25
  clip_len: 50
  dropout_ratio: 0.5
  hidden_dim: 2048


# optim
nesterov: False
weight_decay: 0.0
base_lr: 0.001
optimizer: SGD
step: [80]

# training
device: [2]
batch_size: 8
test_batch_size: 8
num_epoch: 100
stream: 'joint'

# log
save_interval: -1
eval_interval: 5
